;= @echo off
;= rem Call DOSKEY and use this file as the macrofile
;= %SystemRoot%\system32\doskey /listsize=1000 /macrofile=%0%
;= rem In batch mode, jump to the end of the file
;= goto:eof
;= Add aliases below here
e.=explorer .
gl=git log --oneline --all --graph --decorate  $*
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls & printf "Information: Clean the showing data on the screen.\n"
clean=printf '' > "%CMDER_ROOT%\config\.history" & cls & printf "Warning: Histories are gone completely.\n"
history=cat "%CMDER_ROOT%\config\.history"
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
ll=ls -lh
ifconfig=ipconfig
reboot=shutdown -r -t 0
orders=printf "\n" & cat "D:/developments/cmder/Cmder/config/myorders.txt" & printf "\n"